version: "2"

services:
    ci-service-tests:
        depends_on:
            - service-a
        image: wernight/phantomjs
        volumes:
            - ./service-a:/src
        working_dir: /src
        command: ["phantomjs", "service-tests.js"]
